In [27]:
import numpy as np
import pandas as pd
from datetime import datetime
import json


### Importar el archivo ##############################################
df = pd.read_csv("movies_dataset.csv")


### Eliminar columnas ###############################################

# Eliminación de columnas no utilizadas
df = df.drop(columns=["video", "imdb_id", "adult",
             "original_title", "vote_count", "poster_path", "homepage"])


################# Transformar columnas revenue y budget ##############################

# Rellenar los valores nulos de los campos "revenue" y "budget" con 0
#df['revenue'].fillna(0, inplace=True)
#df['budget'].fillna(0, inplace=True)
df['budget'] = pd.to_numeric(df['budget'], errors='coerce').fillna(0).astype(int)
df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce').fillna(0).astype(int)


# Convertir la columna "budget"  y "revenue" a un tipo de datos numérico
#df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
df['budget'] = df['budget'].astype(int)
df['revenue'] = df['revenue'].astype(int)


# Convertir a tipo numérico y eliminar filas con valores no válidos (pide reemplazrlo por 0)
#df['budget'] = pd.to_numeric(df['budget'], errors='coerce')
#df['revenue'] = pd.to_numeric(df['revenue'], errors='coerce')


# Eliminar filas con NaN en las columnas 'budget' y 'revenue'
#df.dropna(subset=['budget', 'revenue'], inplace=True)

###############################################################

###"Transofrar release_date"##############################################

# Convertir la columna "release_date" al formato de fecha
df['release_date'] = pd.to_datetime(df['release_date'], errors='coerce')

# Darle formato AAAA-mm-dd a 'release_date'
df['release_date'] = df['release_date'].dt.strftime('%Y-%m-%d') #2

# Crear la columna "release_year" para extraer el año de la fecha de estreno
#df['release_year'] = df['release_date'].dt.year.fillna(0).astype(int) #1 
df['release_year'] = df['release_date'].str[:4] #2

# Eliminar filas con valores nulos en la columna "release_date"
df.dropna(subset=['release_date'], inplace=True)

##############################################################

### Columna "return"##########################################

# Calcular el retorno de inversión solo cuando revenue y budget son diferentes de 0
# df['return'] = np.where((df['revenue'] != 0) & df['budget'] != 0), (df['revenue'] / df['budget'], 0)
df['return'] = df.apply(lambda row: row['revenue'] / row['budget'] if row['budget'] != 0 else 0, axis=1)


############## DESEMPAQUETADO ###############################

# Columna 'belongs_to_collection'

#split_columns = ['id BtC', 'name', 'poster_path', 'backdrop_path']
#split_data = df['belongs_to_collection'].str.split(',', expand=True)


# Verificar la cantidad de columnas generadas
#num_columns = min(len(split_data.columns), len(split_columns))

# Asignar los valores divididos a las nuevas columnas
#df[split_columns[:num_columns]] = split_data.iloc[:, :num_columns]

#Columna 



##############################################################

C:\Users\Martin\AppData\Local\Temp\ipykernel_3312\2626231030.py:8: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("movies_dataset.csv")
c:\Users\Martin\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\core\dtypes\astype.py:189: RuntimeWarning: invalid value encountered in cast
  return values.astype(dtype, copy=copy)

In [28]:
df.to_csv("output.csv", sep=",", index=False)

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45376 entries, 0 to 45465
Data columns (total 19 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4488 non-null   object
 1   budget                 45376 non-null  int32
 2   genres                 45376 non-null  object
 3   id                     45376 non-null  object
 4   original_language      45365 non-null  object
 5   overview               44435 non-null  object
 6   popularity             45376 non-null  object
 7   production_companies   45376 non-null  object
 8   production_countries   45376 non-null  object
 9   release_date           45376 non-null  object
 10  revenue                45376 non-null  int32
 11  runtime                45130 non-null  float64
 12  spoken_languages       45376 non-null  object
 13  status                 45296 non-null  object
 14  tagline                20398 non-null  object
 15  title                  45376 non-null  object
 16  vote_average           45376 non-null  float64
 17  release_year           45376 non-null  object
 18  return                 45376 non-null  float64
dtypes: float64(3), int32(2), object(14)
memory usage: 6.6+ MB

In [9]:

###CHEQUEO##########################





#Los valores nulos de los campos revenue, budget deben ser rellenados por el número 0.
#Los valores nulos del campo release date deben eliminarse.
null_counts = df.isnull().sum()
null_counts


# De haber fechas, deberán tener el formato AAAA-mm-dd,
# además deberán crear la columna release_year donde extraerán el año de la fecha de estreno.

df[["release_date" , "release_year"]]


#Crear la columna con el retorno de inversión, llamada return con los campos revenue y budget,
#dividiendo estas dos últimas revenue / budget, cuando no hay datos disponibles para calcularlo, 
#deberá tomar el valor 0.

df[['revenue', 'budget', 'return']].head()

#Eliminar las columnas que no serán utilizadas:
#video,imdb_id,adult,original_title,vote_count,poster_path y homepage.

df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45376 entries, 0 to 45465
Data columns (total 23 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   belongs_to_collection  4488 non-null   object
 1   budget                 45376 non-null  int32
 2   genres                 45376 non-null  object
 3   id                     45376 non-null  object
 4   original_language      45365 non-null  object
 5   overview               44435 non-null  object
 6   popularity             45376 non-null  object
 7   production_companies   45376 non-null  object
 8   production_countries   45376 non-null  object
 9   release_date           45376 non-null  object
 10  revenue                45376 non-null  int32
 11  runtime                45130 non-null  float64
 12  spoken_languages       45376 non-null  object
 13  status                 45296 non-null  object
 14  tagline                20398 non-null  object
 15  title                  45376 non-null  object
 16  vote_average           45376 non-null  float64
 17  release_year           45376 non-null  object
 18  return                 45376 non-null  float64
 19  id BtC                 4488 non-null   object
 20  name                   4488 non-null   object
 21  poster_path            4488 non-null   object
 22  backdrop_path          4488 non-null   object
dtypes: float64(3), int32(2), object(18)
memory usage: 8.0+ MB